name: SimpleFlyBoost
version: ${project.version}
api-version: 1.13
main: com.darkender.plugins.simpleflyboost.SimpleFlyBoost
author: Techdoodle
permissions:
  simpleflyboost.boost:
    default: op
  simpleflyboost.freeze:
    default: op